### ISSUE TITLE
Handle YouTube Subcriptions

### ISSUE THREAD

**Issue by pantar85** [z-------------/cumulonimbus#11]
Currently using gpodder. Love this so far, last piece of the puzzle for me is handling youtube channel subscriptions. URL would just be the channels video feed, which by default sorts videos by age [newest first]. youtube-dl could be used to retreive the content.

Food for thought.

Thank you

**Comment by probonopd** [comment]
For me, even more important would be: Subscribe to YouTube searches, e.g., "all videos about AppImage from this week".

**Comment by z-------------** [comment]
@pantar85 and @probonopd, thanks for the suggestions. I'll think about how/whether I'll implement these.

**Comment by probonopd** [comment]
I am really positive that the ability to turn YT channels and searches into podcasts has "killer feature" potential.

While we are at it, https://github.com/TeamNewPipe/NewPipe can also download YT as audio-only.

**Comment by z-------------** [comment]
I'll be sure to look into it.

**Comment by probonopd** [comment]
https://rg3.github.io/youtube-dl/ possibly can do the heavy lifting.

**Comment by z-------------** [comment]
@probonopd, thanks for the recommendation. I've found [a node driver](https://www.npmjs.com/package/youtube-dl) for that program and will probably be using that. Most likely I will use an embedded YouTube player for streaming and only use youtube-dl when downloading for offline consumption.

**Comment by z-------------** [comment]
Commit fbe9fe18314d38c18e2c1d0a45144bf7ca5db02f adds support for YouTube channels as podcasts. Paste the channel URL (e.g. `https://www.youtube.com/user/TheVerge` or `https://www.youtube.com/channel/UCBJycsmduvYEL83R_U4JriQ`) in the search box in Explore to preview and subscribe. This functionality is available in [(pre)release 1.19.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.19.0). Please let me know if there are any problems.

@probonopd, I will have to think about how I am going to handle searches, since they are not inherently chronological. Will split that into a separate issue so I can close this one.
