### ISSUE TITLE
Pre-release auto-updater

### ISSUE THREAD

**Issue by Noahkiq** [z-------------/cumulonimbus#52]
An option to enable automatic checks for new versions would be useful so I don't have to manually check for a new version every few days ;P

**Comment by z-------------** [comment]
CPod actually does have this feature, it's just that it only does automatic updates for "stable releases" and not pre-releases. There are a couple of bugs and new features I want to deal with and locales to update before I put out a new stable.

I will however add a thing in the About section of Settings that checks for new pre-releases so the user can choose to download it. Thanks for the input :)

**Comment by Noammac** [comment]
You could utilise the update information feature of AppImages if you want. It will let anyone using the AppImageUpdate tool to automatically update CPod without any hassle.

**Comment by z-------------** [comment]
@Noammac Thanks for the suggestion though I don't think it will be necessary since the framework I'm using already has a very nice and convenient update system (convenient for the user and for me). One of the use cases AppImageUpdate seems to be for pushing out frequent "nightly" builds — I can add an option in the settings to make the existing update system also check for and download pre-releases.

**Comment by z-------------** [comment]
[(Pre)release 1.22.7](https://github.com/z-------------/cumulonimbus/releases/tag/v1.22.7) adds an option in Settings to include prereleases in the update check. Please let me know if there are any problems.
