### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by willdowglas** [z-------------/cumulonimbus#61]
Hi there. Since the update,  your program does not work, can you help me?
Here is the error message:
![screenshot from 2018-04-30 21-15-46](https://user-images.githubusercontent.com/7102785/39456284-cdd5b2da-4cbb-11e8-9e21-86777bac52a7.png)
Here is my SO info:
![screenshot from 2018-04-30 21-16-40](https://user-images.githubusercontent.com/7102785/39456285-cdf831de-4cbb-11e8-9aad-08ae7a4a4ac9.png)

**Comment by z-------------** [comment]
Hi,
From the error message it looks like CPod is trying to read one of its internal files but finding it invalid. This is really puzzling, because all the relevant calls to JSON.parse are wrapped in a try...catch and should fail gracefully.

Could you please let me know which version of CPod you are using, and attach `user_settings.json` and `window_size` from the CPod user data directory (under $XDG_CONFIG_HOME or ~/.config on Linux)? Thanks.

**Comment by z-------------** [comment]
Hi,
From the error message it looks like CPod is trying to read one of its internal files but finding it invalid. This is really puzzling, because all the calls to JSON.parse near that line number are wrapped in a try...catch and should fail gracefully.

Nevertheless, [(pre)release 1.23.2](https://github.com/z-------------/cumulonimbus/releases/tag/v1.23.2) contains some changes that might fix the problem. Please try it and let me know how it goes.

If that doesn't work, could you please let me know which version of CPod you are using, and attach `user_settings.json` and `window_size` from the CPod user data directory (under $XDG_CONFIG_HOME or ~/.config on Linux)? Thanks.

**Comment by willdowglas** [comment]
So, the version I am currently using is 1.14.0-1, i installed through Pamac. I am trying to reinstall, in order to dont loose my configs, if it doesnt work, i will download and install manually the 1.23.3 version, since i dont know how to update via bash. I will return soon if it worked or not, thanks.

**Comment by willdowglas** [comment]
The reinstall did not work, I will install the current version.
The problem, tho, is that is outdated [here](https://aur.archlinux.org/packages/cpod)
I would like to contribute by updating it in AUR, but I have no idea *how* to do it.

I tried to install, and got this:
```
sudo dpkg -i CPod_1.23.3_amd64.deb
Selecting previously unselected package cumulonimbus.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack CPod_1.23.3_amd64.deb ...
Unpacking cumulonimbus (1.23.3-321) ...
dpkg: dependency problems prevent configuration of cumulonimbus:
 cumulonimbus depends on gconf2; however:
  Package gconf2 is not installed.
 cumulonimbus depends on gconf-service; however:
  Package gconf-service is not installed.
 cumulonimbus depends on libnotify4; however:
  Package libnotify4 is not installed.
 cumulonimbus depends on libappindicator1; however:
  Package libappindicator1 is not installed.
 cumulonimbus depends on libxtst6; however:
  Package libxtst6 is not installed.
 cumulonimbus depends on libnss3; however:
  Package libnss3 is not installed.
 cumulonimbus depends on libxss1; however:
  Package libxss1 is not installed.

dpkg: error processing package cumulonimbus (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 cumulonimbus
```

If you could update the AUR repo, or teach me how to do, I will gladly help. I love podcasts, and really enjoyed your software.

I downloaded the appimage, and was able to run it with my previous configs and listed podcasts, **it works!** It dont have the Cpod icon, and it is installed in my download files, but at least works. Since I was using an outdated version, and I was able to solv my problem, you could close the issue, thank you.

**Comment by z-------------** [comment]
Glad to hear you got it working.

The error you're getting with dpkg seems to be related to [this](https://github.com/atom/atom/issues/14358), so perhaps the solution outlined there will help.

The only official distributions of CPod are the ones here on GitHub, and as such I don't know how to update the AUR distribution.

Thanks.
