### ISSUE TITLE
Unable to subscribe to a particular podcast

### ISSUE THREAD

**Issue by nfugal** [z-------------/cumulonimbus#63]
I'm trying to subscribe to Radio Free Hipster, a music podcast. 
I've tried a couple of different versions of the feed and can't see to get it to stick.
With one version of the feed, I can hit the subscribe button and it changes to say subscrbed but the podcast doesn't show up in my subscription list. I can download episodes and listem to them offline style. 

The following are the feeds that I've tried to use both in explore and improt OPML with no luck:
https://geekdad.com/wp-content/uploads/podcasts/RadioFreeHipster.xml
http://www.hipsterplease.com/rss

**Comment by z-------------** [comment]
Hi, this issue is due to the fact that CPod is not able to find a podcast image from the RSS, which it assumes exists, and consequently fails to subscribe. I'll fix this bug in an upcoming release. Thanks for letting me know about this.

**Comment by z-------------** [comment]
[Pre-release 1.24.1](https://github.com/z-------------/cumulonimbus/releases/tag/v1.24.1) should fix this problem – a placeholder image will be used for podcasts without a valid cover image. Please let me know if there are any problems.

P.S. The second RSS feed will not work because it's missing the actual audio URLs. The first one is fine, though.
