### ISSUE TITLE
Support Chapters

### ISSUE THREAD

**Issue by probonopd** [z-------------/cumulonimbus#9]
Thank you for this extremely useful app. Desktop Linux was seriously missing this! 

Please check out [Podlove Simple Chapters](https://podlove.org/simple-chapters/) to provide for chapter information in podcasts.

Example: https://freakshow.fm/, click on "Chapters"

![freakshow](https://user-images.githubusercontent.com/2480569/33031889-d3638ad0-ce1f-11e7-94de-d70eb087af57.png)

Would be cool to see this or similar functionality in cumulonimbus. And [shownot.es](https://shownot.es/archive/)!

**Comment by z-------------** [comment]
Thanks for the suggestion, I'll look into adding this soon.

**Comment by ZetaoYang** [comment]
@probonopd Hi, there are also [Vocal](http://vocalproject.net/) and [gPodder](https://gpodder.github.io/) for Desktop Linux. Vocal is so good as well as cumulonimbus.
BTW, @z-------------  the name of "cumulonimbus" is too long.😄

**Comment by z-------------** [comment]
@ZetaoYang 😄 I noticed that too but I haven't been able to think of a good new name.

**Comment by probonopd** [comment]
Vocal is not available as an AppImage and does not run on my systems, and gPodder is very minimalistic. So I'm really happy to have this project with the name that I can neither remember nor speak ;-)

**Comment by ZetaoYang** [comment]
@probonopd 
Because vocal miss the dependency "libgranite.so.3", I put "libgranite.so.3" into lib folder and  re-package them. I upload the deb file,you can download it. [vocal_2.0.20-2_amd64.deb.zip](https://github.com/z-------------/cumulonimbus/files/1498399/vocal_2.0.20-2_amd64.deb.zip)   
And now vocal work well under pure Ubuntu 16.04. P.S.  "libgranite.so.3" is one of elementary os libraries.


![image](https://user-images.githubusercontent.com/10769951/33163842-3f9faa92-d06b-11e7-82de-01ce1bf958cc.png)

![image](https://user-images.githubusercontent.com/10769951/33163629-65ada8d4-d06a-11e7-8f87-3286e8da76a4.png)

![image](https://user-images.githubusercontent.com/10769951/33163687-9811c31e-d06a-11e7-91c1-d6c569860386.png)

![image](https://user-images.githubusercontent.com/10769951/33164604-8224c23c-d06e-11e7-966d-a88987c79daa.png)

**Comment by probonopd** [comment]
@ZetaoYang but I am running Ubuntu 14.04 LTS. culum...bus runs fine on it.

**Comment by z-------------** [comment]
@probonopd I've added support for PSC chapters in [release 1.8.0](https://github.com/z-------------/cumulonimbus/releases/tag/v1.8.0). _Freak Show_ downloads incredibly slowly on my end and I haven't been able to find other podcasts that embed PSC information, so could you please try it out and tell me if anything is missing. Thanks.

I'm going to split the Shownotes request into a separate issue so I can mark this one as closed if the chapters feature is ok.

**Comment by probonopd** [comment]
I can confirm that Podlove Simple Chapters are working great. Thank you very much!

![](https://user-images.githubusercontent.com/2480569/34437038-2aeffefc-ec9b-11e7-8031-58273819a294.png)
